name: Instagram Poster
on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install instagrapi Pillow==10.0.0 python-dotenv
          
      - name: Run Instagram bot
        env:
          SECRETS: ${{ secrets.SECRETS }}
        run: python post.py
